#this is the where you set the resources and patches. The below is just an example 

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./vendor/karpenter/
- ./resources/nodetemplates.yaml
- ./resources/provisioners.yaml
patches:
- path: ./patches/configmap.yaml
- path: ./patches/serviceaccount.yaml
