apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./vendor/karpenter/
- ./resources/nodetemplates.yaml
- ./resources/provisioners.yaml
patches:
- path: ./patches/configmap.yaml
- path: ./patches/serviceaccount.yaml
